//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastwayShopifyAppV3.AramexLocation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string VersionField;
        
        private string AccountNumberField;
        
        private string AccountPinField;
        
        private string AccountEntityField;
        
        private string AccountCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredLanguageCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AccountPin {
            get {
                return this.AccountPinField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPinField, value) != true)) {
                    this.AccountPinField = value;
                    this.RaisePropertyChanged("AccountPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string AccountEntity {
            get {
                return this.AccountEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountEntityField, value) != true)) {
                    this.AccountEntityField = value;
                    this.RaisePropertyChanged("AccountEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string AccountCountryCode {
            get {
                return this.AccountCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCountryCodeField, value) != true)) {
                    this.AccountCountryCodeField = value;
                    this.RaisePropertyChanged("AccountCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PreferredLanguageCode {
            get {
                return this.PreferredLanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageCodeField, value) != true)) {
                    this.PreferredLanguageCodeField = value;
                    this.RaisePropertyChanged("PreferredLanguageCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Reference1Field;
        
        private string Reference2Field;
        
        private string Reference3Field;
        
        private string Reference4Field;
        
        private string Reference5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference1 {
            get {
                return this.Reference1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference1Field, value) != true)) {
                    this.Reference1Field = value;
                    this.RaisePropertyChanged("Reference1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference2 {
            get {
                return this.Reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference2Field, value) != true)) {
                    this.Reference2Field = value;
                    this.RaisePropertyChanged("Reference2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference3 {
            get {
                return this.Reference3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference3Field, value) != true)) {
                    this.Reference3Field = value;
                    this.RaisePropertyChanged("Reference3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference4 {
            get {
                return this.Reference4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference4Field, value) != true)) {
                    this.Reference4Field = value;
                    this.RaisePropertyChanged("Reference4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference5 {
            get {
                return this.Reference5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference5Field, value) != true)) {
                    this.Reference5Field = value;
                    this.RaisePropertyChanged("Reference5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Line1Field;
        
        private string Line2Field;
        
        private string Line3Field;
        
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceCodeField;
        
        private string PostCodeField;
        
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StateOrProvinceCode {
            get {
                return this.StateOrProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceCodeField, value) != true)) {
                    this.StateOrProvinceCodeField = value;
                    this.RaisePropertyChanged("StateOrProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string POBox {
            get {
                return this.POBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.POBoxField, value) != true)) {
                    this.POBoxField = value;
                    this.RaisePropertyChanged("POBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string NameField;
        
        private string IsoCodeField;
        
        private bool StateRequiredField;
        
        private bool PostCodeRequiredField;
        
        private string[] PostCodeRegexField;
        
        private string InternationalCallingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool StateRequired {
            get {
                return this.StateRequiredField;
            }
            set {
                if ((this.StateRequiredField.Equals(value) != true)) {
                    this.StateRequiredField = value;
                    this.RaisePropertyChanged("StateRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool PostCodeRequired {
            get {
                return this.PostCodeRequiredField;
            }
            set {
                if ((this.PostCodeRequiredField.Equals(value) != true)) {
                    this.PostCodeRequiredField = value;
                    this.RaisePropertyChanged("PostCodeRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string[] PostCodeRegex {
            get {
                return this.PostCodeRegexField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeRegexField, value) != true)) {
                    this.PostCodeRegexField = value;
                    this.RaisePropertyChanged("PostCodeRegex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string InternationalCallingNumber {
            get {
                return this.InternationalCallingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InternationalCallingNumberField, value) != true)) {
                    this.InternationalCallingNumberField = value;
                    this.RaisePropertyChanged("InternationalCallingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Office : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityField;
        
        private string EntityDescriptionField;
        
        private string OfficeTypeField;
        
        private FastwayShopifyAppV3.AramexLocation.Address AddressField;
        
        private string TelephoneField;
        
        private string WorkingDaysField;
        
        private string WorkingHoursField;
        
        private decimal LongtitudeField;
        
        private decimal LatitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EntityDescription {
            get {
                return this.EntityDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityDescriptionField, value) != true)) {
                    this.EntityDescriptionField = value;
                    this.RaisePropertyChanged("EntityDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OfficeType {
            get {
                return this.OfficeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeTypeField, value) != true)) {
                    this.OfficeTypeField = value;
                    this.RaisePropertyChanged("OfficeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public FastwayShopifyAppV3.AramexLocation.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string WorkingDays {
            get {
                return this.WorkingDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingDaysField, value) != true)) {
                    this.WorkingDaysField = value;
                    this.RaisePropertyChanged("WorkingDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string WorkingHours {
            get {
                return this.WorkingHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingHoursField, value) != true)) {
                    this.WorkingHoursField = value;
                    this.RaisePropertyChanged("WorkingHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class State : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressServiceDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class AddressServiceDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ProductGroupField;
        
        private string ProductTypeField;
        
        private int ServiceModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductGroup {
            get {
                return this.ProductGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGroupField, value) != true)) {
                    this.ProductGroupField = value;
                    this.RaisePropertyChanged("ProductGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceMode {
            get {
                return this.ServiceModeField;
            }
            set {
                if ((this.ServiceModeField.Equals(value) != true)) {
                    this.ServiceModeField = value;
                    this.RaisePropertyChanged("ServiceMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName="AramexLocation.Service_1_0")]
    public interface Service_1_0 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddress", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddressResponse")]
        FastwayShopifyAppV3.AramexLocation.AddressValidationResponse ValidateAddress(FastwayShopifyAppV3.AramexLocation.AddressValidationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddress", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ValidateAddressResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.AddressValidationResponse> ValidateAddressAsync(FastwayShopifyAppV3.AramexLocation.AddressValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountries", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountriesResponse")]
        FastwayShopifyAppV3.AramexLocation.CountriesFetchingResponse FetchCountries(FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountries", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountriesResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CountriesFetchingResponse> FetchCountriesAsync(FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountry", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountryResponse")]
        FastwayShopifyAppV3.AramexLocation.CountryFetchingResponse FetchCountry(FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountry", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCountryResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CountryFetchingResponse> FetchCountryAsync(FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCities", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCitiesResponse")]
        FastwayShopifyAppV3.AramexLocation.CitiesFetchingResponse FetchCities(FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCities", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchCitiesResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CitiesFetchingResponse> FetchCitiesAsync(FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOffices", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOfficesResponse")]
        FastwayShopifyAppV3.AramexLocation.OfficesFetchingResponse FetchOffices(FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOffices", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchOfficesResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.OfficesFetchingResponse> FetchOfficesAsync(FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchStates", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchStatesResponse")]
        FastwayShopifyAppV3.AramexLocation.StatesFetchingResponse FetchStates(FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchStates", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/FetchStatesResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.StatesFetchingResponse> FetchStatesAsync(FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/IsAddressServiced", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/IsAddressServicedResponse")]
        FastwayShopifyAppV3.AramexLocation.AddressServiceabilityResponse IsAddressServiced(FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/IsAddressServiced", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/IsAddressServicedResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.AddressServiceabilityResponse> IsAddressServicedAsync(FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressValidationRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressValidationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public FastwayShopifyAppV3.AramexLocation.Address Address;
        
        public AddressValidationRequest() {
        }
        
        public AddressValidationRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Address Address) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressValidationResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressValidationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.Address[] SuggestedAddresses;
        
        public AddressValidationResponse() {
        }
        
        public AddressValidationResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexLocation.Address[] SuggestedAddresses) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.SuggestedAddresses = SuggestedAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountriesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountriesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        public CountriesFetchingRequest() {
        }
        
        public CountriesFetchingRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountriesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountriesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.Country[] Countries;
        
        public CountriesFetchingResponse() {
        }
        
        public CountriesFetchingResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexLocation.Country[] Countries) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Countries = Countries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountryFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string Code;
        
        public CountryFetchingRequest() {
        }
        
        public CountryFetchingRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string Code) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CountryFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.Country Country;
        
        public CountryFetchingResponse() {
        }
        
        public CountryFetchingResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexLocation.Country Country) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Country = Country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CitiesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CitiesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string CountryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public string NameStartsWith;
        
        public CitiesFetchingRequest() {
        }
        
        public CitiesFetchingRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode, string State, string NameStartsWith) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.CountryCode = CountryCode;
            this.State = State;
            this.NameStartsWith = NameStartsWith;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CitiesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class CitiesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public string[] Cities;
        
        public CitiesFetchingResponse() {
        }
        
        public CitiesFetchingResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, string[] Cities) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Cities = Cities;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OfficesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class OfficesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string CountryCode;
        
        public OfficesFetchingRequest() {
        }
        
        public OfficesFetchingRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.CountryCode = CountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OfficesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class OfficesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.Office[] Offices;
        
        public OfficesFetchingResponse() {
        }
        
        public OfficesFetchingResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexLocation.Office[] Offices) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.Offices = Offices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatesFetchingRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class StatesFetchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public string CountryCode;
        
        public StatesFetchingRequest() {
        }
        
        public StatesFetchingRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.CountryCode = CountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatesFetchingResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class StatesFetchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.State[] States;
        
        public StatesFetchingResponse() {
        }
        
        public StatesFetchingResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexLocation.State[] States) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.States = States;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressServiceabilityRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressServiceabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public FastwayShopifyAppV3.AramexLocation.Address Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexLocation.AddressServiceDetails ServiceDetails;
        
        public AddressServiceabilityRequest() {
        }
        
        public AddressServiceabilityRequest(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Address Address, FastwayShopifyAppV3.AramexLocation.AddressServiceDetails ServiceDetails) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.Address = Address;
            this.ServiceDetails = ServiceDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddressServiceabilityResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class AddressServiceabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexLocation.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexLocation.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public System.Nullable<bool> IsServiced;
        
        public AddressServiceabilityResponse() {
        }
        
        public AddressServiceabilityResponse(FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Notification[] Notifications, bool HasErrors, System.Nullable<bool> IsServiced) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.IsServiced = IsServiced;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_1_0Channel : FastwayShopifyAppV3.AramexLocation.Service_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_1_0Client : System.ServiceModel.ClientBase<FastwayShopifyAppV3.AramexLocation.Service_1_0>, FastwayShopifyAppV3.AramexLocation.Service_1_0 {
        
        public Service_1_0Client() {
        }
        
        public Service_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.AddressValidationResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.ValidateAddress(FastwayShopifyAppV3.AramexLocation.AddressValidationRequest request) {
            return base.Channel.ValidateAddress(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] ValidateAddress(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Address Address, out bool HasErrors, out FastwayShopifyAppV3.AramexLocation.Address[] SuggestedAddresses) {
            FastwayShopifyAppV3.AramexLocation.AddressValidationRequest inValue = new FastwayShopifyAppV3.AramexLocation.AddressValidationRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.Address = Address;
            FastwayShopifyAppV3.AramexLocation.AddressValidationResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).ValidateAddress(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            SuggestedAddresses = retVal.SuggestedAddresses;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.AddressValidationResponse> ValidateAddressAsync(FastwayShopifyAppV3.AramexLocation.AddressValidationRequest request) {
            return base.Channel.ValidateAddressAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.CountriesFetchingResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.FetchCountries(FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest request) {
            return base.Channel.FetchCountries(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] FetchCountries(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, out bool HasErrors, out FastwayShopifyAppV3.AramexLocation.Country[] Countries) {
            FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest inValue = new FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            FastwayShopifyAppV3.AramexLocation.CountriesFetchingResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).FetchCountries(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            Countries = retVal.Countries;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CountriesFetchingResponse> FetchCountriesAsync(FastwayShopifyAppV3.AramexLocation.CountriesFetchingRequest request) {
            return base.Channel.FetchCountriesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.CountryFetchingResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.FetchCountry(FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest request) {
            return base.Channel.FetchCountry(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] FetchCountry(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string Code, out bool HasErrors, out FastwayShopifyAppV3.AramexLocation.Country Country) {
            FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest inValue = new FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.Code = Code;
            FastwayShopifyAppV3.AramexLocation.CountryFetchingResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).FetchCountry(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            Country = retVal.Country;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CountryFetchingResponse> FetchCountryAsync(FastwayShopifyAppV3.AramexLocation.CountryFetchingRequest request) {
            return base.Channel.FetchCountryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.CitiesFetchingResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.FetchCities(FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest request) {
            return base.Channel.FetchCities(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] FetchCities(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode, string State, string NameStartsWith, out bool HasErrors, out string[] Cities) {
            FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest inValue = new FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.CountryCode = CountryCode;
            inValue.State = State;
            inValue.NameStartsWith = NameStartsWith;
            FastwayShopifyAppV3.AramexLocation.CitiesFetchingResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).FetchCities(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            Cities = retVal.Cities;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.CitiesFetchingResponse> FetchCitiesAsync(FastwayShopifyAppV3.AramexLocation.CitiesFetchingRequest request) {
            return base.Channel.FetchCitiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.OfficesFetchingResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.FetchOffices(FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest request) {
            return base.Channel.FetchOffices(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] FetchOffices(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode, out bool HasErrors, out FastwayShopifyAppV3.AramexLocation.Office[] Offices) {
            FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest inValue = new FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.CountryCode = CountryCode;
            FastwayShopifyAppV3.AramexLocation.OfficesFetchingResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).FetchOffices(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            Offices = retVal.Offices;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.OfficesFetchingResponse> FetchOfficesAsync(FastwayShopifyAppV3.AramexLocation.OfficesFetchingRequest request) {
            return base.Channel.FetchOfficesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.StatesFetchingResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.FetchStates(FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest request) {
            return base.Channel.FetchStates(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] FetchStates(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, string CountryCode, out bool HasErrors, out FastwayShopifyAppV3.AramexLocation.State[] States) {
            FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest inValue = new FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.CountryCode = CountryCode;
            FastwayShopifyAppV3.AramexLocation.StatesFetchingResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).FetchStates(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            States = retVal.States;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.StatesFetchingResponse> FetchStatesAsync(FastwayShopifyAppV3.AramexLocation.StatesFetchingRequest request) {
            return base.Channel.FetchStatesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexLocation.AddressServiceabilityResponse FastwayShopifyAppV3.AramexLocation.Service_1_0.IsAddressServiced(FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest request) {
            return base.Channel.IsAddressServiced(request);
        }
        
        public FastwayShopifyAppV3.AramexLocation.Notification[] IsAddressServiced(FastwayShopifyAppV3.AramexLocation.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexLocation.Transaction Transaction, FastwayShopifyAppV3.AramexLocation.Address Address, FastwayShopifyAppV3.AramexLocation.AddressServiceDetails ServiceDetails, out bool HasErrors, out System.Nullable<bool> IsServiced) {
            FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest inValue = new FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.Address = Address;
            inValue.ServiceDetails = ServiceDetails;
            FastwayShopifyAppV3.AramexLocation.AddressServiceabilityResponse retVal = ((FastwayShopifyAppV3.AramexLocation.Service_1_0)(this)).IsAddressServiced(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            IsServiced = retVal.IsServiced;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexLocation.AddressServiceabilityResponse> IsAddressServicedAsync(FastwayShopifyAppV3.AramexLocation.AddressServiceabilityRequest request) {
            return base.Channel.IsAddressServicedAsync(request);
        }
    }
}
