//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastwayShopifyAppV3.AramexRate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string VersionField;
        
        private string AccountNumberField;
        
        private string AccountPinField;
        
        private string AccountEntityField;
        
        private string AccountCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredLanguageCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AccountPin {
            get {
                return this.AccountPinField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPinField, value) != true)) {
                    this.AccountPinField = value;
                    this.RaisePropertyChanged("AccountPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string AccountEntity {
            get {
                return this.AccountEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountEntityField, value) != true)) {
                    this.AccountEntityField = value;
                    this.RaisePropertyChanged("AccountEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string AccountCountryCode {
            get {
                return this.AccountCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCountryCodeField, value) != true)) {
                    this.AccountCountryCodeField = value;
                    this.RaisePropertyChanged("AccountCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PreferredLanguageCode {
            get {
                return this.PreferredLanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredLanguageCodeField, value) != true)) {
                    this.PreferredLanguageCodeField = value;
                    this.RaisePropertyChanged("PreferredLanguageCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Reference1Field;
        
        private string Reference2Field;
        
        private string Reference3Field;
        
        private string Reference4Field;
        
        private string Reference5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference1 {
            get {
                return this.Reference1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference1Field, value) != true)) {
                    this.Reference1Field = value;
                    this.RaisePropertyChanged("Reference1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference2 {
            get {
                return this.Reference2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference2Field, value) != true)) {
                    this.Reference2Field = value;
                    this.RaisePropertyChanged("Reference2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference3 {
            get {
                return this.Reference3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference3Field, value) != true)) {
                    this.Reference3Field = value;
                    this.RaisePropertyChanged("Reference3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference4 {
            get {
                return this.Reference4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference4Field, value) != true)) {
                    this.Reference4Field = value;
                    this.RaisePropertyChanged("Reference4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference5 {
            get {
                return this.Reference5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Reference5Field, value) != true)) {
                    this.Reference5Field = value;
                    this.RaisePropertyChanged("Reference5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Line1Field;
        
        private string Line2Field;
        
        private string Line3Field;
        
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceCodeField;
        
        private string PostCodeField;
        
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StateOrProvinceCode {
            get {
                return this.StateOrProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceCodeField, value) != true)) {
                    this.StateOrProvinceCodeField = value;
                    this.RaisePropertyChanged("StateOrProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string POBox {
            get {
                return this.POBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.POBoxField, value) != true)) {
                    this.POBoxField = value;
                    this.RaisePropertyChanged("POBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class ShipmentDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FastwayShopifyAppV3.AramexRate.Dimensions DimensionsField;
        
        private FastwayShopifyAppV3.AramexRate.Weight ActualWeightField;
        
        private FastwayShopifyAppV3.AramexRate.Weight ChargeableWeightField;
        
        private string DescriptionOfGoodsField;
        
        private string GoodsOriginCountryField;
        
        private int NumberOfPiecesField;
        
        private string ProductGroupField;
        
        private string ProductTypeField;
        
        private string PaymentTypeField;
        
        private string PaymentOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money CustomsValueAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money CashOnDeliveryAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money InsuranceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money CashAdditionalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashAdditionalAmountDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money CollectAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.ShipmentItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.DeliveryInstructions DeliveryInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.AdditionalProperty[] AdditionalPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FastwayShopifyAppV3.AramexRate.Dimensions Dimensions {
            get {
                return this.DimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsField, value) != true)) {
                    this.DimensionsField = value;
                    this.RaisePropertyChanged("Dimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public FastwayShopifyAppV3.AramexRate.Weight ActualWeight {
            get {
                return this.ActualWeightField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualWeightField, value) != true)) {
                    this.ActualWeightField = value;
                    this.RaisePropertyChanged("ActualWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public FastwayShopifyAppV3.AramexRate.Weight ChargeableWeight {
            get {
                return this.ChargeableWeightField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeableWeightField, value) != true)) {
                    this.ChargeableWeightField = value;
                    this.RaisePropertyChanged("ChargeableWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string DescriptionOfGoods {
            get {
                return this.DescriptionOfGoodsField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionOfGoodsField, value) != true)) {
                    this.DescriptionOfGoodsField = value;
                    this.RaisePropertyChanged("DescriptionOfGoods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string GoodsOriginCountry {
            get {
                return this.GoodsOriginCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsOriginCountryField, value) != true)) {
                    this.GoodsOriginCountryField = value;
                    this.RaisePropertyChanged("GoodsOriginCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumberOfPieces {
            get {
                return this.NumberOfPiecesField;
            }
            set {
                if ((this.NumberOfPiecesField.Equals(value) != true)) {
                    this.NumberOfPiecesField = value;
                    this.RaisePropertyChanged("NumberOfPieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string ProductGroup {
            get {
                return this.ProductGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGroupField, value) != true)) {
                    this.ProductGroupField = value;
                    this.RaisePropertyChanged("ProductGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentOptions {
            get {
                return this.PaymentOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentOptionsField, value) != true)) {
                    this.PaymentOptionsField = value;
                    this.RaisePropertyChanged("PaymentOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public FastwayShopifyAppV3.AramexRate.Money CustomsValueAmount {
            get {
                return this.CustomsValueAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomsValueAmountField, value) != true)) {
                    this.CustomsValueAmountField = value;
                    this.RaisePropertyChanged("CustomsValueAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public FastwayShopifyAppV3.AramexRate.Money CashOnDeliveryAmount {
            get {
                return this.CashOnDeliveryAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.CashOnDeliveryAmountField, value) != true)) {
                    this.CashOnDeliveryAmountField = value;
                    this.RaisePropertyChanged("CashOnDeliveryAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public FastwayShopifyAppV3.AramexRate.Money InsuranceAmount {
            get {
                return this.InsuranceAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceAmountField, value) != true)) {
                    this.InsuranceAmountField = value;
                    this.RaisePropertyChanged("InsuranceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public FastwayShopifyAppV3.AramexRate.Money CashAdditionalAmount {
            get {
                return this.CashAdditionalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.CashAdditionalAmountField, value) != true)) {
                    this.CashAdditionalAmountField = value;
                    this.RaisePropertyChanged("CashAdditionalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string CashAdditionalAmountDescription {
            get {
                return this.CashAdditionalAmountDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CashAdditionalAmountDescriptionField, value) != true)) {
                    this.CashAdditionalAmountDescriptionField = value;
                    this.RaisePropertyChanged("CashAdditionalAmountDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public FastwayShopifyAppV3.AramexRate.Money CollectAmount {
            get {
                return this.CollectAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectAmountField, value) != true)) {
                    this.CollectAmountField = value;
                    this.RaisePropertyChanged("CollectAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public FastwayShopifyAppV3.AramexRate.ShipmentItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public FastwayShopifyAppV3.AramexRate.DeliveryInstructions DeliveryInstructions {
            get {
                return this.DeliveryInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryInstructionsField, value) != true)) {
                    this.DeliveryInstructionsField = value;
                    this.RaisePropertyChanged("DeliveryInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public FastwayShopifyAppV3.AramexRate.AdditionalProperty[] AdditionalProperties {
            get {
                return this.AdditionalPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalPropertiesField, value) != true)) {
                    this.AdditionalPropertiesField = value;
                    this.RaisePropertyChanged("AdditionalProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dimensions", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Dimensions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LengthField;
        
        private double WidthField;
        
        private double HeightField;
        
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weight", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Weight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UnitField;
        
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Money", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Money : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CurrencyCodeField;
        
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryInstructions", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class DeliveryInstructions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OptionField;
        
        private string ReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Option {
            get {
                return this.OptionField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionField, value) != true)) {
                    this.OptionField = value;
                    this.RaisePropertyChanged("Option");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentItem", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class ShipmentItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PackageTypeField;
        
        private int QuantityField;
        
        private FastwayShopifyAppV3.AramexRate.Weight WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Dimensions[] PiecesDimensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommodityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryOfOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FastwayShopifyAppV3.AramexRate.Money CustomsValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PackageType {
            get {
                return this.PackageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageTypeField, value) != true)) {
                    this.PackageTypeField = value;
                    this.RaisePropertyChanged("PackageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FastwayShopifyAppV3.AramexRate.Weight Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public FastwayShopifyAppV3.AramexRate.Dimensions[] PiecesDimensions {
            get {
                return this.PiecesDimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PiecesDimensionsField, value) != true)) {
                    this.PiecesDimensionsField = value;
                    this.RaisePropertyChanged("PiecesDimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CommodityCode {
            get {
                return this.CommodityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommodityCodeField, value) != true)) {
                    this.CommodityCodeField = value;
                    this.RaisePropertyChanged("CommodityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string GoodsDescription {
            get {
                return this.GoodsDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsDescriptionField, value) != true)) {
                    this.GoodsDescriptionField = value;
                    this.RaisePropertyChanged("GoodsDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CountryOfOrigin {
            get {
                return this.CountryOfOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryOfOriginField, value) != true)) {
                    this.CountryOfOriginField = value;
                    this.RaisePropertyChanged("CountryOfOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public FastwayShopifyAppV3.AramexRate.Money CustomsValue {
            get {
                return this.CustomsValueField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomsValueField, value) != true)) {
                    this.CustomsValueField = value;
                    this.RaisePropertyChanged("CustomsValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ContainerNumber {
            get {
                return this.ContainerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerNumberField, value) != true)) {
                    this.ContainerNumberField = value;
                    this.RaisePropertyChanged("ContainerNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalProperty", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class AdditionalProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryNameField;
        
        private string NameField;
        
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    [System.SerializableAttribute()]
    public partial class RateDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double AmountField;
        
        private double OtherAmount1Field;
        
        private double OtherAmount2Field;
        
        private double OtherAmount3Field;
        
        private double OtherAmount4Field;
        
        private double OtherAmount5Field;
        
        private double TotalAmountBeforeTaxField;
        
        private double TaxAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount1 {
            get {
                return this.OtherAmount1Field;
            }
            set {
                if ((this.OtherAmount1Field.Equals(value) != true)) {
                    this.OtherAmount1Field = value;
                    this.RaisePropertyChanged("OtherAmount1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount2 {
            get {
                return this.OtherAmount2Field;
            }
            set {
                if ((this.OtherAmount2Field.Equals(value) != true)) {
                    this.OtherAmount2Field = value;
                    this.RaisePropertyChanged("OtherAmount2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount3 {
            get {
                return this.OtherAmount3Field;
            }
            set {
                if ((this.OtherAmount3Field.Equals(value) != true)) {
                    this.OtherAmount3Field = value;
                    this.RaisePropertyChanged("OtherAmount3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount4 {
            get {
                return this.OtherAmount4Field;
            }
            set {
                if ((this.OtherAmount4Field.Equals(value) != true)) {
                    this.OtherAmount4Field = value;
                    this.RaisePropertyChanged("OtherAmount4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount5 {
            get {
                return this.OtherAmount5Field;
            }
            set {
                if ((this.OtherAmount5Field.Equals(value) != true)) {
                    this.OtherAmount5Field = value;
                    this.RaisePropertyChanged("OtherAmount5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double TotalAmountBeforeTax {
            get {
                return this.TotalAmountBeforeTaxField;
            }
            set {
                if ((this.TotalAmountBeforeTaxField.Equals(value) != true)) {
                    this.TotalAmountBeforeTaxField = value;
                    this.RaisePropertyChanged("TotalAmountBeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double TaxAmount {
            get {
                return this.TaxAmountField;
            }
            set {
                if ((this.TaxAmountField.Equals(value) != true)) {
                    this.TaxAmountField = value;
                    this.RaisePropertyChanged("TaxAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName="AramexRate.Service_1_0")]
    public interface Service_1_0 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRate", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRateResponse")]
        FastwayShopifyAppV3.AramexRate.RateCalculatorResponse CalculateRate(FastwayShopifyAppV3.AramexRate.RateCalculatorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRate", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRateResponse")]
        System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexRate.RateCalculatorResponse> CalculateRateAsync(FastwayShopifyAppV3.AramexRate.RateCalculatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateCalculatorRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class RateCalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexRate.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public FastwayShopifyAppV3.AramexRate.Address OriginAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexRate.Address DestinationAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public FastwayShopifyAppV3.AramexRate.ShipmentDetails ShipmentDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=5)]
        public string PreferredCurrencyCode;
        
        public RateCalculatorRequest() {
        }
        
        public RateCalculatorRequest(FastwayShopifyAppV3.AramexRate.ClientInfo ClientInfo, FastwayShopifyAppV3.AramexRate.Transaction Transaction, FastwayShopifyAppV3.AramexRate.Address OriginAddress, FastwayShopifyAppV3.AramexRate.Address DestinationAddress, FastwayShopifyAppV3.AramexRate.ShipmentDetails ShipmentDetails, string PreferredCurrencyCode) {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.OriginAddress = OriginAddress;
            this.DestinationAddress = DestinationAddress;
            this.ShipmentDetails = ShipmentDetails;
            this.PreferredCurrencyCode = PreferredCurrencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateCalculatorResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class RateCalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public FastwayShopifyAppV3.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public FastwayShopifyAppV3.AramexRate.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public FastwayShopifyAppV3.AramexRate.Money TotalAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public FastwayShopifyAppV3.AramexRate.RateDetails RateDetails;
        
        public RateCalculatorResponse() {
        }
        
        public RateCalculatorResponse(FastwayShopifyAppV3.AramexRate.Transaction Transaction, FastwayShopifyAppV3.AramexRate.Notification[] Notifications, bool HasErrors, FastwayShopifyAppV3.AramexRate.Money TotalAmount, FastwayShopifyAppV3.AramexRate.RateDetails RateDetails) {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.TotalAmount = TotalAmount;
            this.RateDetails = RateDetails;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_1_0Channel : FastwayShopifyAppV3.AramexRate.Service_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_1_0Client : System.ServiceModel.ClientBase<FastwayShopifyAppV3.AramexRate.Service_1_0>, FastwayShopifyAppV3.AramexRate.Service_1_0 {
        
        public Service_1_0Client() {
        }
        
        public Service_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FastwayShopifyAppV3.AramexRate.RateCalculatorResponse FastwayShopifyAppV3.AramexRate.Service_1_0.CalculateRate(FastwayShopifyAppV3.AramexRate.RateCalculatorRequest request) {
            return base.Channel.CalculateRate(request);
        }
        
        public FastwayShopifyAppV3.AramexRate.Notification[] CalculateRate(FastwayShopifyAppV3.AramexRate.ClientInfo ClientInfo, ref FastwayShopifyAppV3.AramexRate.Transaction Transaction, FastwayShopifyAppV3.AramexRate.Address OriginAddress, FastwayShopifyAppV3.AramexRate.Address DestinationAddress, FastwayShopifyAppV3.AramexRate.ShipmentDetails ShipmentDetails, string PreferredCurrencyCode, out bool HasErrors, out FastwayShopifyAppV3.AramexRate.Money TotalAmount, out FastwayShopifyAppV3.AramexRate.RateDetails RateDetails) {
            FastwayShopifyAppV3.AramexRate.RateCalculatorRequest inValue = new FastwayShopifyAppV3.AramexRate.RateCalculatorRequest();
            inValue.ClientInfo = ClientInfo;
            inValue.Transaction = Transaction;
            inValue.OriginAddress = OriginAddress;
            inValue.DestinationAddress = DestinationAddress;
            inValue.ShipmentDetails = ShipmentDetails;
            inValue.PreferredCurrencyCode = PreferredCurrencyCode;
            FastwayShopifyAppV3.AramexRate.RateCalculatorResponse retVal = ((FastwayShopifyAppV3.AramexRate.Service_1_0)(this)).CalculateRate(inValue);
            Transaction = retVal.Transaction;
            HasErrors = retVal.HasErrors;
            TotalAmount = retVal.TotalAmount;
            RateDetails = retVal.RateDetails;
            return retVal.Notifications;
        }
        
        public System.Threading.Tasks.Task<FastwayShopifyAppV3.AramexRate.RateCalculatorResponse> CalculateRateAsync(FastwayShopifyAppV3.AramexRate.RateCalculatorRequest request) {
            return base.Channel.CalculateRateAsync(request);
        }
    }
}
